### ISSUE TITLE
Lab 11 ASA Job does not have option to "Add Storage Account" anymore

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#100]
# Module: 06
##### Step: 01

The UI has changed and does not allow for creating a storage account from there anymore.

Repro steps:

1. On the Stream Analytics job blade, on the left side navigation menu under Configure, click Storage account settings.
1. On the Storage account settings pane, click Add storage account.
1. There is no "Add storage account"

**Comment by darenm** [comment]
New versions of the labs have been published so closing this issue.
