### ISSUE TITLE
Lab: 14 -> Task: Exercice 3: -> Step:7 - Set up the IoT Edge Parent with Child IoT Devices

### ISSUE THREAD

**Issue by cjvaland** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#102]
# Module: 07
#### Step: 07

Description of issue
--pd is not a valid parameter as described in the course:
--pd: This parameter specifies the Parent Device for the IoT Device being created. The value passed in must be the Device ID of the Parent Device to assign this Child Device to.

Repro steps:

When you run this command it fails in Cloud Shell:
 az iot hub device-identity create -n iot-az220-training-{your-id} --device-id sensor-th-0084 --pd vm-az220-training-gw0002-{your-id}
Error:
unrecognized arguments: -pd vm-az220-training-gw0002-{your-id}

The documentation doens't also mention anything about this parameter
https://docs.microsoft.com/en-us/cli/azure/iot/hub/device-identity?view=azure-cli-latest#az_iot_hub_device_identity_create

**Comment by mkennten** [comment]
Looks like the extension got updated and we should use "az iot hub device-identity children add", see
"https://docs.microsoft.com/en-us/cli/azure/iot/hub/device-identity/children?view=azure-cli-latest for this now.

**Comment by darenm** [comment]
New versions of the labs have been published so closing this issue.
