### ISSUE TITLE
Lab 10 -> Exercise 2: Setup Time Series Insights -> Error: environmentTimeSeriesIdProperties not provided

### ISSUE THREAD

**Issue by pradorodriguez** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#103]
# Module: 05
#### Step: 22

Description of issue: 
The current steps will fail at step 22. The service is requesting for the "environmentTimeSeriesIdProperties". The problems seems to be related to the new TSI version and the new Tier Price option (Gen L2). The Gen L2 requires a new "Time series ID" property which seems to be conflicting with the old version.

Repro steps:
1.
1.
1.

**Comment by darenm** [comment]
New versions of the labs have been published so closing this issue.
