### ISSUE TITLE
Lab 19 -> Exercise 8 -> Task 4 -> Step 4

### ISSUE THREAD

**Issue by pradorodriguez** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#109]
# Module: 11
#### Step: 04

Description of issue: Getting "error AZF0001" inside Function "[FunctionName("HubToAdtFunction")]" when building or deploying code.
Specific error: ...\HubToAdtFunction.cs(25,34): error AZF0001: Async void can lead to unexpected behavior. Return Task instead. ...\Contoso.AdtFunctions\Contoso.AdtFunctions.csproj]

Repro steps:

1. dotnet build or deploy code to Azure Function
1.
1.

**Comment by pradorodriguez** [comment]
Error reference: https://docs.microsoft.com/en-us/azure/azure-functions/errors-diagnostics/sdk-rules/azf0001

**Comment by darenm** [comment]
New versions of the labs have been published so closing this issue.
