### ISSUE TITLE
Failed to Start IoT Edge Daemon 

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#118]
#  Module 6: Azure IoT Edge Deployment Process
#### Step: 07

Description of issue 

Azure IoT Edge Daemon failed to start. I have searched this in GitHub and found several others to be having issues due to docker not running. ( [940](https://github.com/Azure/iotedge/issues/940) & [11046](https://github.com/MicrosoftDocs/azure-docs/issues/11046))

so I tried: **systemctl status docker**

This showed docker was active and running (top of screenshot).

Then running commands to restart iotedge after editing the doc.
Then the command to check the status shows the error. 

Steps:

To ensure the IoT Edge daemon is running, enter the following command:

**sudo systemctl status iotedge**

---

**Screenshot of Issues encountered in the UI:**

![2021-09-30_141730](https://user-images.githubusercontent.com/62302805/135511125-c9989d7d-0f24-4eb9-aec8-f99a189377ad.JPG)

**Comment by darenm** [comment]
New versions of the labs have been published so closing this issue.
