### ISSUE TITLE
Lab 20 Ex 5-6, error Code 401000

### ISSUE THREAD

**Issue by sstas911** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#119]
# Module: 12
#### Step: 2

Lab20 Ex 6, Task1, 
In Visual Studio Code, in the Terminal command prompt, i enter command: dotnet run
Message **"Starting Truck number 1"** is displayed. 
But after that i receive ERROR message in terminal window:

ProvisioningClient RegisterAsync...
{"errorCode":401000,"trackingId":"a5c087cd-31b3-4ccd-afb9-236e1313d386","message":"Unauthorized","timestampUtc":"2021-10-13T09:00:13.2276933Z"}

I have checked all credentials: ID scope, SAS,  Azure MapsKey - all is correct.

Need help to identify how to fix it.

Repro steps:

1.
1.
![github issue](https://user-images.githubusercontent.com/60794119/137110635-261050c7-a312-4560-91ba-1e06f2a2fca0.jpg)
1.

**Comment by darenm** [comment]
New versions of the labs have been published so closing this issue.
