### ISSUE TITLE
Mod 19, Ex4, Task 4, Step 1 - Deprecated Download Link

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#120]
# Module: 19
#### Step: 01

Description of issue
Link seems deprecated for downloading DTDL Validator, recommend leveraging  github.com/Azure-Samples/DTDL-Validator/releases instead.

1.
1.
1.

**Comment by darenm** [comment]
New versions of the labs have been published so closing this issue.
