### ISSUE TITLE
Mod 18, Ex 2, Task 1, Step 13 - Unable to Secure Function

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#122]
# Module: 18
#### Step: 03

Description of issue
Clicking the Secure Iot Function button appears to be non functioning with an Azure pass. 

Attempted the following from cloudshell: 

`systemctl status defender-iot-micro-agent.service`
`systemctl start defender-iot-micro-agent.service`

The command throws an error. I have reached out to Microsoft on this.

**Comment by darenm** [comment]
New versions of the labs have been published so closing this issue.
