### ISSUE TITLE
Lab 8 is missing

### ISSUE THREAD

**Issue by jimbobbennett** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#129]
# Module: 05
#### Step: 00

Description of issue

The link to lab 8 gives a 404, and there is no lab 8 markdown file in the [labs](https://github.com/MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer/tree/master/Instructions/Labs) folder.

**Comment by darenm** [comment]
Lab 8 has been withdrawn and is no longer part of the course. We shall look into why the auto-generated index is still listing it.
