### ISSUE TITLE
Provide architecture diagram

### ISSUE THREAD

**Issue by RipinAggarwal** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#13]
Hi Team,

Thanks a lot for sharing the rich content. Its really great and easy to follow.
**One Suggestion**, can you please include the architectural diagram, where every feasible, to better understand the task. 

Regards,
Ripin Aggarwal

**Comment by ChrisHowd** [comment]
Thanks for the feedback Ripin. We will update the instructor notes with your suggestion.

Chris Howd

**Comment by darenm** [comment]
@RipinAggarwal This is currently a work in-progress.

**Comment by darenm** [comment]
@RipinAggarwal Architecture diagrams have been added to the instructor notes and to the lab scenarios.
