### ISSUE TITLE
Error in deploying devices. Labs Broken.

### ISSUE THREAD

**Issue by pilleryann** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#131]
# Module: 05
#### Step: 09

Description of issue :
When I deploy the ARM template of the Lab, I have a deployment error on the devices deployments part. 
With this error, the labs are broken.  I think other labs with multiple devices deployment are also broken.

The details of error are in the attached files.

Repro steps:

1.  Open the lab
2.  Use the template for this lab 

[Deployment-createDevice-sensor-thl-container0001.zip](https://github.com/MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer/files/7923571/Deployment-createDevice-sensor-thl-container0001.zip)
.

**Comment by ChrisHowd** [comment]
Thanks for reporting this issue. A work-around is being developed while we investigate the policy issues impacting the MS Learn lab sandbox and the lab hosting environments.
