### ISSUE TITLE
Lab 04 "Deploy to Azure" does not open in LODS

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#134]
## Lab: 04
Exercise: 1
Task: 1

Description of issue
The "Deploy to Azure" link is not opened in LODS but on the personal computer browser. This may irritate students. The link also cannot be copied to the LODS machine.

Suggestion:
a) open the link on the LODS machine
OR
b) provide the link as Text [T] and ask students to paste it into the LODS browser

**Comment by ChrisHowd** [comment]
lab instructions updated (manually enter url for template)
