### ISSUE TITLE
Change on IoT Hub blade - Lab 04 (and probably others)

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#135]
## Lab 04
Excercise 2
#### Step: 04

Description of issue
It reads: On the left-side menu of your IoT Hub blade, under Explorers, click IoT devices.

Change to:
On the left-side menu of your IoT Hub blade, under **Device management,** click **Devices**

**Comment by ChrisHowd** [comment]
thanks for reporting the issue. lab instructions have been updated.
