### ISSUE TITLE
Lab 04 

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#136]
## Lab 04
Exercise 3
Task 1
#### Step: 05

Description of issue
I get the error "Tere are no versions available for the package 'Microsoft.Azure.Devices.Client'.

Fix:
Run the command
   dotnet nuget add source --name nuget.org https://api.nuget.org/v3/index.json
then run the command 
   dotnet add package Microsoft.Azure.Devices.Client

**Comment by ChrisHowd** [comment]
Thanks for your feedback. The lab instructions have been updated.
