### ISSUE TITLE
Lab 13 deployment script missing

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#137]
Lab 13: Develop, Deploy and debug a custom module on Azure IoT Edge with VS Code
Exercise 1: Verify Lab Prerequesits
### Task: 00

Description of issue
Code-box reads
"The **Custom deployment** page will be displayed."
There is no link embedded to start the custom deployment

Repro steps:
Add the correct link to Deploy the resources

**Comment by ChrisHowd** [comment]
thanks for reporting this issue. the lab instructions have been updated
