### ISSUE TITLE
Instructions are for Windows, not other platforms

### ISSUE THREAD

**Issue by jimbobbennett** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#14]
# Module: AZ-220
#### Step: 02

Description of issue

Although there is a brief note about installing VS Code on other platforms, the majority of the text assumes the user is on Windows. For example:

`On the Download Visual Studio Code page, click Windows`

`By default, Visual Studio Code is installed in the “C:\Program Files (x86)\Microsoft VS Code” folder`

Can this be updated to reflect all supported platforms, including macOS and Linux.

Repro steps:

1. Use a Mac
1. Follow the instructions

**Comment by jimbobbennett** [comment]
Same for Task 4:

`On the Windows 10 Start menu, to begin installing the Azure PowerShell tools, right-click Windows Powershell, and then click Run as Administrator.`

I don't have a Windows 10 start menu on my Mac. Does this work with PowerShell Core on a Mac? Are there ways to achieve the same result on a Mac or Linux box?

**Comment by jimbobbennett** [comment]
The answer to the PowerShell on core question is no. It works up till step 6:

`Import-Module -Name AzureRM`

The error given is:

```sh
Import-Module : Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.                                                                                                                         At /Users/jimbennett/.local/share/powershell/Modules/AzureRM.profile/5.8.2/AzureRM.Profile.psm1:81 char:1                                              + Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...                                                                            + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException                                                                     + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand  
```

**Comment by MikeBazMSFT** [comment]
This is a 100% legit callout.  We've tried to avoid those kinds of situations but obviously we haven't caught them everywhere.  I'm leaving this issue open so that we don't lose track of this kind of thing.  

We appreciate you calling this out and please continue to keep us honest here :)

**Comment by jimbobbennett** [comment]
@MikeBazMSFT - are you accepting PRs? If so I'll try to find time to make some tweaks.

**Comment by MikeBazMSFT** [comment]
Indeed we are - you're welcome to tackle it.  We've already accepted some PRs (not many but a few) :)

**Comment by darenm** [comment]
@jimbobbennett  Thanks for reporting. As an update, these labs were written to target a specific training VM running Windows 10, hence the Windows-specific nature of the steps. Therefore, the initial versions of the labs will continue to target Windows exclusively. As the changes to support MacOS are relatively small, we will add that task to the backlog for a future version of the labs.

As you noted, the AzureRM module is Windows-specific, however we will be updating the content to use the **Az** module instead, that will run on PowerShell.Core on MacOS.
