### ISSUE TITLE
Instruction of L07-analyze-message-data-in-real-time is inverted with the L08-visualize-data-stream-in-power-bi

### ISSUE THREAD

**Issue by vhyrodrigues** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#16]
# Module: 07
#### Step: 00

Description of issue
The instruction of the L07-analyze-message-data-in-real-time are inverted with the L08-visualize-data-stream-in-power-bi
Repro steps:

1.
1.
1.

**Comment by MikeBazMSFT** [comment]
I'm sorry, I'm not sure what you're trying to say here?

**Comment by darenm** [comment]
@vhyrodrigues thanks for creating an issue. Although we are uncertain what you meant with your original issue, L07 and L08 have been refreshed since you created it. I will close this issue now - if you continue to see issues with 07 and 08, please open a new issue.
