### ISSUE TITLE
Lab 8 not in the correct module

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#17]
# Module: 05
## Lab/Demo: 08

According with MOC the Lab 8: Visualize Data in Power BI is part of Module 5 and not module 4.

I wanted to leave one  suggestion. Instead of using AzureRM modules, switch to Az modules. My suggestion is because the other Azure MOCs are using Az modules, it is not possible to have the AzureRM and AZ modules installed simultaneously and Az modules is compatible with PowerShell Core.

Thanks

**Comment by MikeBazMSFT** [comment]
hey @ChrisHowd can you check the current internal working MOC and see where we have this lab?  

The module callout is an excellent one and we should look across all the labs at that.

**Comment by MikeBazMSFT** [comment]
It looks like lab 8 is showing in Module 5 in the Module 5 internal working copy of the PowerPoint, and in the current listing information here.  So I think we're consistent there?

I'm leaving this open because of the other concern around the PowerPoint module.

**Comment by darenm** [comment]
@rramoscabral @MikeBazMSFT I do not see any occurrence of PowerShell and the AzureRM modules in the current version of LAB_AZ_08.
@rramoscabral  Are you referring to elsewhere such as the setup in LAB_AK_03? I will create another issue to update that setup.
