### ISSUE TITLE
LAB 09 image uri is incorrect

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#18]
# Module: 05
#### Step: 2.24 , 2.26, and 3.31

Description of issue

The URI images is incorrect. For example the  [HTTP request info](../../Linked_Image_files/MM99-L09-subscription-form.png) is not pointed to "https://github.com/MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer/blob/master/MSLearn/Linked_Image_Files/MM99-L09-subscription-form.png"

At exercise 3 I think the task number 31 is typo.  

Repro steps:

1. From https://microsoftlearning.github.io/AZ-220-Microsoft-Azure-IoT-Developer/ 
2. Select Lab 09: Integrate IoT Hub with Event Grid 
3. Exercise 3,  click in the subscription event types url image
2. File not found 404.
3. URL: https://microsoftlearning.github.io/AZ-220-Microsoft-Azure-IoT-Developer/Linked_Image_files/MM99_L09_http_post.png

**Comment by MikeBazMSFT** [comment]
As mentioned in the known issues, most (all) image references are broken right now.  I'm looking at the other stuff now :)

**Comment by MikeBazMSFT** [comment]
ok, "31" is fixed, thanks for pointing out that embarrassing typo 😳... also fixed the indenting in that general area so the numbering flows right now.
