### ISSUE TITLE
Lab 13 incorrect IoT Edge Module named

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#19]
# Module: 7
#### Step: 7

Description of issue

At step 7 the custom IoT Edge Module named is "ObjectCountingModule" and it is necessary to change to "ObjectCounterModule" because the followings steps:
- Exercise 1, step 8 the uri for the repository is set to "localhost:5000/objectcountermodule"
- "Exercise 6: Deploy IoT Edge Solution", beginning step 22 and the next steps.

**Comment by rramoscabral** [comment]
Is better to change the name custom IoT Edge Module named to "ObjectCounterModule" in step 7, exercise 1. Because step 22 and the next steps in "Exercise 6: Deploy IoT Edge Solution"

**Comment by MikeBazMSFT** [comment]
I caught this over the weekend while reviewing the lab.  I'm still finishing up my review so I'm leaving this open, but when I get the reviewed version published this should be fixed.

**Comment by MikeBazMSFT** [comment]
ok I actually changed it to ObjectCountingModule but that was somewhat a matter of personal choice for me.  I just pushed the fixed version (also has some other important fixes like adding the missing `docker login` step) so hopefully we'll be in better shape on this one.

I forgot to tag the issue with the commit :(

thanks for opening the issue :)
