### ISSUE TITLE
C# you might see:

### ISSUE THREAD

**Issue by gerhard67** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#2]
# Module: 00
#### Step: Publicly Visible Resources

Description of issue
'_Again, private string _yourId = "{YOUR-ID}"; should be updated to private string _yourId = "{CAH191216}";_'

shouldn't this be: '...updated to private string _yourId = "CAH191216";' without {}?

**Comment by MikeBazMSFT** [comment]
yup, it should be.  There's another related typo in that area as well; I just fixed both.  Thanks for the report!
