### ISSUE TITLE
Issue with certs when doing L12 and L11 has already been done

### ISSUE THREAD

**Issue by AltusBaard** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#20]
# Module: 6
#### Step: 20

Description of issue
When coming from Lab 11 with all steps and tasks completed, once you try to download the certificates a permission denied error is thrown, meaning the certificates from L11 will remain, causing exercise 9 step 15 to throw an invalid certificate error.

Repro steps:

1. Complete Lab 11
1. Follow exercises for Lab 12
1. Once you reach exercise 3 step 20 a permission error is thrown

**Comment by MikeBazMSFT** [comment]
I was going to comment that I didn't understand you issue as Lab 11 doesn't have any certificates (except the SSH host certificate), but I realize Lab 06 does.  You're right, there's a potential conflict in the ~/certificates folders in the Cloud Shell.  I'm up to Lab 12 on my current cleanup pass myself so I'll sort this out soon, likely by changing the name of the folder in Lab 12 to a new folder name.  Sit tight and thanks for calling this out.

**Comment by AltusBaard** [comment]
Yes sorry, I meant to say that when you have done all labs up till 11 and then proceed to 12, you get the error.

I ended up just creating a new sub directory and working from there

**Comment by MikeBazMSFT** [comment]
OK, I think the updated version of Lab 12 fixed this - changed the name of the folder everywhere to "lab12" instead of "certificates"... I think I got it right.  I tested that way and it seemed okay.
