### ISSUE TITLE
Lab 11 missing reference to required ARM template

### ISSUE THREAD

**Issue by dabrock51** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#203]
# Module: 6
#### Step: 1-2

Description of issue
This instruction appears to be written to deploy a custom ARM tenplate, however, there is nothing indicating what template we should be using. It would need to be a Linux VM that includes an IoT Edge runtime.

**Comment by ChrisHowd** [comment]
thanks for identifying the issue. the lab instructions have been updated.

**Comment by dabrock51** [comment]
Thanks. Just so you know, you have an identical issue in Lab 12 at the same point in the lab, a missing ARM template declaration.
