### ISSUE TITLE
Lab 17 - 19 Name too long in ARM template

### ISSUE THREAD

**Issue by dabrock51** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#204]
#### Step: 1

Description of issue
Instructions call out deploying an ARM template.

The validation of the templates fails because the name supplied for the storage account exceeds the maximum number of characters (24). This appears to be because the naming convention used in the template plus the recommended unique id size (9 characters - iiiyymmdd) exceed the maximum value allowed.

Screenshot attached.
![ARM-template-failure](https://user-images.githubusercontent.com/32367563/156663582-50397a2e-01b2-4c86-9014-298284cd1822.png)

**Comment by ChrisHowd** [comment]
thanks for identifying the issue. the template has been updated to accommodate
