### ISSUE TITLE
Module 03, Lab 06: Dotnet application does not build

### ISSUE THREAD

**Issue by mhykgyver** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#210]
# Module: 03
##### Step: 22

Description of issue
   It does not build, tons of code missing from starter code

Repro steps:
Follow all steps until step 22 and it will not build due to missing code

Solution:
Use the code in the final folder, all missing codes are available and can compare with the starter code

**Comment by ChrisHowd** [comment]
Thanks for the feedback. Lab instructions have been updated to specify "Final" folder rather than "Starter" folder.
