### ISSUE TITLE
Times series lab - Exercise 4 has an issue

### ISSUE THREAD

**Issue by prabhjotsinghbakshi** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#217]
Description of issue - 
Cannot log into the TSI Explorer as a account  user   ( user not allowed ) while performing the exercise 4 ( step no 3) 

error code
Selected user account does not exist in tenant 'Microsoft Services' and cannot access the application '120d688d-1518-4cf7-bd38-182f158850b6' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account.

**Comment by test4293** [comment]
I am also facing similar issue, any resolutions?

**Comment by prabhjotsinghbakshi** [comment]
Try this as it worked for me --
Step 1- Add a new user to the tenant (AAD) like tsi@tenant.onmicrosoft.com
Step 2- Make him owner of the Subscription
Step 3- In the Time Series Insights environment OVERVIEW window - under setting section- goto DATA Access TIER and add TSI user as a Contributor
Step 4- Then when you click on "Go TO TSI Explorer" - next window login as tsi user ( do not use personal id )
Hope this works for you as well
