### ISSUE TITLE
Lab 19 problem starting ASCIoTAgent.service (no usable version of the libssl was found)

### ISSUE THREAD

**Issue by surfen** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#22]
# Module: 10
##### Step: 07

The ASCIoIAgent.service fails to start. Following the linked article did not help much: [Deploy Azure Security Center for IoT C# based security agent for Linux Guide Troubleshooting Section](https://docs.microsoft.com/en-us/azure/asc-for-iot/how-to-deploy-linux-cs).

The lab seems unfinished due to the fact that no recommendations are presented by Azure Security Center. How to simulate the tampering to see a threat or recommendation in the Security Center?

Repro steps:

1. Follow all steps in the lab until excercise 6, task 4, step 7
1. Check the status: `systemctl status ASCIoTAgent.service`
1. execute `journalctl` and scroll down, notice the message: `No usable version of the libssl was found`
1. Solve by installing libssl1.0.0 (similar problem: https://github.com/dbcli/mssql-cli/issues/252)

> $ wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb
> $ sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb

**Comment by darenm** [comment]
Dashboard and Custom Alerts
Completed Azure Security Center Dashboard Section
Added Custom Alerts section
