### ISSUE TITLE
lab 02, ex 4, Task 2: Create a Device Provisioning Service with required property settings

### ISSUE THREAD

**Issue by nish112** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#222]
# Module: 00
#### Step: 00

Description of issue
I am facing an issue in creation of device provisioning service in azure. I am getting an error "subscription not found". I have a valid subscription and using the same subscription i am able to create iot hub and other resources.

I also tried with multiple regions like east us, west us 2 and central india, all in vain.

Please suggest what to do.
Repro steps:
Follow the steps mentioned in lab 02, ex 4, Task 2: Create a Device Provisioning Service with required property settings

Please suggest what to do.
1.
1.
1.

**Comment by nish112** [comment]
As i have mentioned before, subscription is valid and working and I am able
to create multiple resources with the same subscription. I have tried both
portal and cli but the same issue persist.

**Comment by prabhjotsinghbakshi** [comment]
if you use Azure pass Subscription issue persist But on using your MSDN subscription no error

**Comment by prabhjotsinghbakshi** [comment]
Pay as you go Subscription(for  account created with credit card )it   works  fine

**Comment by nish112** [comment]
It seems there was some issue on azure side, as earlier creation of dps was giving error (i tried with azure pass, MSDN). Now, it is working and i checked with both azure pass and MSDN subscription.
