### ISSUE TITLE
Lab 10: Custom Deployment failed, conflict in createDevice step

### ISSUE THREAD

**Issue by pauldeng** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#224]
# Module: AZ-220-Microsoft-Azure-IoT-Developer
#### Step: 9

Description of issue
Failed to create the Custom deployment.
![image](https://user-images.githubusercontent.com/341848/170913753-bb0dcb21-8179-4c9f-9553-79ceb328f9aa.png)

`
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{\r\n  \"status\": \"failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentScriptOperationFailed\",\r\n        \"message\": \"Resource 'eo6f4jxp4elryazscripts' was disallowed by policy. Policy identifiers: '[{\\\"policyAssignment\\\":{\\\"name\\\":\\\"AZ220MSL-ACP-Lab10\\\",\\\"id\\\":\\\"/subscriptions/00bc24e5-80f4-4394-afad-f8bd3ca2a68f/resourceGroups/ResourceGroup1lod23753134/providers/Microsoft.Authorization/policyAssignments/policyAssignment1589\\\"},\\\"policyDefinition\\\":{\\\"name\\\":\\\"AZ220MSL-ACP-Lab10\\\",\\\"id\\\":\\\"/subscriptions/00bc24e5-80f4-4394-afad-f8bd3ca2a68f/providers/Microsoft.Authorization/policyDefinitions/policy1589\\\"}}]'.\"\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}
`

Repro steps:

1. Follow the steps
2. Failed to create the custom deployment

**Comment by ChrisHowd** [comment]
It appears that the deployment failed during the createDevice operation. This can occur for some Azure account types the template tries to use a managed identity to create the IoT devices. I will update the lab instructions to include a work-around.

You can complete the following steps to create the required IoT devices and a record of the IoT hub and device connections strings.

    1. On the Azure portal menu, click **Dashboard**.

    1. On the All resources tile, to open your IoT hub, click iot-az220-training-{your-id}.

    1. On the IoT hub blade, under Device management, click Devices.

    1. On the Devices page, click + Add Device.

    1. On the Create a device page, under Device ID, enter sensor-th-truck0001

    1. At the bottom of the page, click Save.

    1. Repeat the previous three steps to create IoT devices with Device IDs of sensor-th-airplane0001 and sensor-th-container0001.

    1. On the Devices page, under Device ID, click sensor-th-truck0001.

        If the device isn't listed, on the Devices page, click Refresh.

    1. On the sensor-th-truck0001 page, to the right of the Device ID value, click Copy, and then save the value to your text editor file.

    1. On the sensor-th-truck0001 page, copy the Primary Connection String value, and then save it to your text editor file.

    1. Repeat the previous three steps to record the Device IDs and Primary Connection String values for the sensor-th-airplane0001 and sensor-th-container0001 devices.

    1. Navigate back to your IoT hub blade.

    1. On the left side menu, under Security settings, click Shared access policies.

    1. Click iothubowner.

    1. Notice that the IoT hub Primary Connection String is listed.

    1. Copy the value of the IoT hub Primary Connection String and save it to your text editor file.
