### ISSUE TITLE
Lab 10: Failed to create TSI Environment

### ISSUE THREAD

**Issue by pauldeng** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#225]
# Module: AZ-220-Microsoft-Azure-IoT-Developer
#### Step: 22

Description of issue
Failed to create TSI Environment.
Validation failed. Required information is missing or not valid on the tab.
![image](https://user-images.githubusercontent.com/341848/171072763-2ea510e9-89d1-49f4-ae38-00a4b494879e.png)

Here are my configurations:
![image](https://user-images.githubusercontent.com/341848/171072863-2810b218-31c2-4152-b123-e00e05c06fd3.png)
![image](https://user-images.githubusercontent.com/341848/171072904-ed0cf74f-548f-45c4-ae2e-1317d88642e0.png)

Thanks.

**Comment by ChrisHowd** [comment]
Thanks for submitting the issue and all the details.
