### ISSUE TITLE
Instructional code Azure Active Directory (Azure AD) Graph Deprecation

### ISSUE THREAD

**Issue by J-O-S-H-C** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#226]
# Module: AZ-220
#### Step: 8

Description of issue

Instructions use "az ad signed-in-user show --query objectId -o tsv" bash command to pull objectID. The objectID property has changed to id due to deprecation of Azure Active Directory Graph. The results do not actually display the id or output a file.

![image](https://user-images.githubusercontent.com/39581053/171913321-2c311515-0158-4f6e-a449-6a8f8c2df6c4.png)
Link from error message: https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration

**Comment by ChrisHowd** [comment]
thanks for pointing our this issue and identifying the proper fix.
