### ISSUE TITLE
Lab 17: Preflight validation failed

### ISSUE THREAD

**Issue by pauldeng** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#228]
# Module: AZ-220-Microsoft-Azure-IoT-Developer
#### Step: 8

Description of issue
Try to load custom deployment, but failed and got this error.
![image](https://user-images.githubusercontent.com/341848/172292445-3820be3f-7d9a-49f2-be9c-ffea088feed0.png)

Repro steps:
1. Follow the steps
2. Failed in the custom deployment validation

**Comment by ChrisHowd** [comment]
Thanks for reporting the issue.
