### ISSUE TITLE
Lab 04/05/06 (Possibly all) Cloud shell doesn't work

### ISSUE THREAD

**Issue by SammyWhamy** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#229]
## Module:  Explore device configuration and communication 
**Lab/Demo: 04**
**Task: 03**
**Step: 09**

#### Description of issue
After Step 09, creating a cloud shell, this error pops up in the shell:
`Requesting a Cloud Shell.Failed to provision a Cloud Shell: {"code":"TenantDisabled","message":"Cloud shell has been disabled in directory '4cc4dc8e-28ab-4b08-b517-2bd1d26defaa'."}`

#### Repro steps:
1. Follow the steps as mentioned
2. Create the storage account
3. Observe the error in the shell

**Comment by SammyWhamy** [comment]
Update 2:
When selecting my default region (West europe) I get a huge error at the top looking something like
`Error: 403 RequestDisallowedByPolicy`
I can't seem to copy the error cause it is in the lab, but it seems to be easily reproducable

Switching to US West 2 (The region my other lab resources are in) produces the same error as originally mentioned

**Comment by ChrisHowd** [comment]
Thanks for reporting the issue

**Comment by adomigar** [comment]
Any update on the issue? The same thing happens to me in the labs that require cloud shell.
