### ISSUE TITLE
Lab 20 GetRouteDirections failing due to coordinates being formated with commas in certain cultures

### ISSUE THREAD

**Issue by surfen** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#23]
# Module: 11
#### Task: 05

The truck does not correctly process commands to go to specific customer due to culture-specfic formatting of the coordinates. GetRouteDirections returns an error message: 

> The provided coordinates in query are invalid, out of range, or not in the expected format

Current code - depends on CurrentCulture - coordinates are incorrectly formatted as numbers with comma (,) as decimal separator 
`var req = new RouteRequestDirections
            {
                Query = $"{currentLat},{currentLon}:{destinationLat},{destinationLon}"
            };`

Corrected code - depends on InvariantCulture - coordinates are formatted as numbers with dot (.) as decimal separator
`var req = new RouteRequestDirections
            {
                Query = FormattableString.Invariant($"{currentLat},{currentLon}:{destinationLat},{destinationLon}")
            };`

**Comment by MikeBazMSFT** [comment]
wow, this is a very very good catch, thanks. 🥇  If you have time to do a PR I'll accept it, otherwise I'll leave this open until I get to this lab in the current review pass.  I fear we may have this issue in other places as well.  :(
