### ISSUE TITLE
Lab 13 - Max retries exceeded with URL

### ISSUE THREAD

**Issue by oedze** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#231]
#### Step: 1

Description of issue
When i click "Build and Run Iot Edge Solution in Simulator the Docker build is succesfull but i get a error message that 
a connecton to my iot Hub iot-az220-tranining-{my id}.azure-devices.net was unsuccesfull because  proxy error occured .
 
![image](https://user-images.githubusercontent.com/5046365/190615794-ead6fcfb-8f7c-4fc7-9c70-9697e51c559b.png)

Repro steps:

1. Do Lab 13 until Task 3,
2. Right click the deployment.debu.template.json
3. Wait for error.

I tried some things, like starting VS Code as Admin,

This is happening in the Labclient, i am not using VSCode on my own pc.
Trying on my PC is not a easy option for me since i don't have Docker or admin rights to install a lot of stuff.

**Comment by ChrisHowd** [comment]
Thanks for reporting the issue
