### ISSUE TITLE
Lab 8 - The instruction documentation needs some updating.

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#235]
# Lab/Demo: 08
#### Step: 11

Description of issue
 The instruction documentation needs some updating.

Repro steps:

1. Exercise 2, Task 1, Step 11 => "Leave Enable Log Analytics set to No." is not in the azure portal.

### Lab

Lab 8: Integrate IoT Hub with Event Grid

### Relevant screenshots

1. Exercise 2, Task 1, Step 11, Screenshots

![image](https://user-images.githubusercontent.com/111972688/201059823-5f0f0330-526d-41ea-af0b-cf00dcee5ebb.png)

**Comment by ChrisHowd** [comment]
Update completed through PR
