### ISSUE TITLE
Lab 8 - Instruction does not match Azure portal

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#236]
# Lab/Demo: 08
#### Step: 01, 02, 03, 04

Description of issue
Instruction does not match Azure portal. I couldn't go further after this step.

Repro steps:

1. Exercise 2, Task 2, Step 1-4 => "Logic Apps Designer" is not in the azure portal.

### Lab

Lab 8: Integrate IoT Hub with Event Grid

### Relevant screenshots

1. Exercise 2, Task 2, Step 1-4, Screenshots

![image](https://user-images.githubusercontent.com/111972688/201061055-f0907403-50de-4339-bafc-fdb7659be384.png)

**Comment by ChrisHowd** [comment]
Could not reproduce reported issue
