### ISSUE TITLE
Lab 15 - Instructions documentation needs some updating.

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#238]
# Lab/Demo: 15
#### Step: 03, 04, 9, 12, 13, 14

Description of issue
Instructions documentation needs some updating.

Repro steps:

1. Exercise 3, Task 2, Step 3 => "Configurations" from instructions should change to "Configurations + Deployments".
2. Exercise 3, Task 2, Step 4 => "+ Add Device Configuration" from instructions should change to "+ Add, from dropdown list, click 
Device Twin Configuration".
3. Exercise 3, Task 2, Step 9, 12, 13, 14 => Steps 12, 13, 14 should move before step 9.

### Lab

Lab 15: Automate IoT Device Management with Azure IoT Hub

### Pull Request

https://github.com/MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer/pull/243

### Relevant screenshots

1. Exercise 3, Task 2, Step 3, 4, Screenshots

![image](https://user-images.githubusercontent.com/111972688/201077246-2cdd7aa2-d3eb-452c-a585-2f83fead008c.png)

3. Exercise 3, Task 2, Step 9, 12, 13, 14, Screenshots

![image](https://user-images.githubusercontent.com/111972688/201080624-a2e3578e-ab64-42c7-9e99-d0da9b7ad391.png)

**Comment by ChrisHowd** [comment]
Update completed through PR
