### ISSUE TITLE
Lab 13 - Instructions documentation needs some updating

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#239]
# Lab/Demo: 13
#### Step: 00

Description of issue
Instructions documentation needs some updating.

Repro steps:

1. Exercise 4, => There are two "Task 1", the second "Task 1" should change to "Task 2",
   "Task 2" to "Task 3" and "Task 3" to "Task 4".

### Lab

Lab 13: Run an IoT Edge device in restricted network and offline

### Relevant screenshots

1. Exercise 4, Screenshots

![image](https://user-images.githubusercontent.com/111972688/201089649-fbd5328d-579d-4960-8f20-8fb9f99b0e30.png)

**Comment by ChrisHowd** [comment]
Update completed through PR
