### ISSUE TITLE
Lab 14 - Instructions documentation needs some updating

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#240]
# Lab/Demo: 14
#### Step: 00

Description of issue
Instructions documentation needs some updating.

Repro steps:

1. Exercise 3 => There are two "Task 3", the first "Task 3" should change to "Task 2".

### Lab

Lab 14: Remotely monitor and control devices with Azure IoT Hub

### Pull Request

https://github.com/MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer/pull/244

### Relevant screenshots

1. Exercise 3, Screenshots

![image](https://user-images.githubusercontent.com/111972688/201090396-f840ce70-456b-42b7-8803-bd1d33f4533d.png)

**Comment by ChrisHowd** [comment]
Update completed through PR
