### ISSUE TITLE
Lab no 14 :issue to find  labfiles setup-iot-edge-gateway.sh and setup-remote-iot-edge-gateway.sh for this lab in the labfile  

### ISSUE THREAD

**Issue by microsoftazureiot** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#25]
# Module: 00
#### Step: 00

Description of issue
There is no labfile  setup-iot-edge-gateway.sh and setup-remote-iot-edge-gateway.sh in the gitlab file file 
Repro steps:

1.
1.
1.

**Comment by MikeBazMSFT** [comment]
Ugh - I thought I had caught this.  OK, thanks for reporting.

your user name is interesting, are you on the product team?  if not you might want to consider renaming.

**Comment by ChrisHowd** [comment]
the two files have been added to the Setup folder for lab 14 (under Allfiles at root).
