### ISSUE TITLE
LAB09 Use sample payload to generate schema clarification request

### ISSUE THREAD

**Issue by Maarten-Work** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#28]
# Lab/Demo: 09
#### Step: 05

Description of issue

Even though technically the description in Step 05 is correct, the individual working through the lab just finds sample JSON without any context to be copied into a textbox. It might leave folks behind puzzled, not really understanding what they are doing.

Instead, I like to suggest referring to the existing documentation (from which the sample JSON was copied). For instance by replacing step 05 by the following:

05) In the **Request Body JSON Schema** textbox, past in a **DeviceCreated** sample event schema, that can be found in the [Event Schema IoT Hub documentation](https://docs.microsoft.com/en-us/azure/event-grid/event-schema-iot-hub). Event Grid will post an event to the Web Hook endpoint for the Logic App.

The end result is the same, but hopefully people taking the lab gain a little more understanding of what they are actually doing by reading over the relevant parts of the Event Trigger documentation. I am sure my description can be clarified even more, but at least people will get more context by reading through the linked documentation and they can easy copy the sample JSON from there. 

Best regards,
Maarten

**Comment by ChrisHowd** [comment]
Thanks for the suggestion Maarten.
