### ISSUE TITLE
Lab 12: Hostname of IOTEdge VM must be lowercase to match DNS Name

### ISSUE THREAD

**Issue by steffigro** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#30]
# Module: Setup an IoT Edge Gateway
#### Step: Task 5/ 19 and Task 6 /4

Description of issue:
sudo iotedge check command raises a misconfiguration error in the config.yaml file due to mismatch of the Hostname of the VM vs. the Hostname (=DNS) name that has been changed in the .yaml file.

Changing the Hostname of the VM to Lowercase resolves the issue.

Repro steps:

1. Create VM using the name AZ-220-VM-EDGEGW-{YOUR-ID} (upper case)
1. Change name from a local Hostname AZ-220-VM-EDGEGW-{YOUR-ID} to the DNS Name that requires lowercase letters, example:  az-220-vm-edgegw-{your-id}.westeurope.cloudapp.azure.com
and change the hostname field in the config.yaml to reflect the change

--> error in IotEdge check

Message: 
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
× config.yaml has correct hostname - Error
    config.yaml has hostname az-220-vm-edgegw-sg070488.westeurope.cloudapp.azure.com but device reports hostname AZ-220-VM-EDGEGW-SG070488.
    Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.

![image](https://user-images.githubusercontent.com/12628477/78779226-de520e00-799c-11ea-99c1-2057c30fe331.png)

SOLUTION: Editing the hostname file using sudo nano /etc/hostname after the wrong VM Name has already been in place resolves the issue. Alternatively, the VM could be created using a lowercase name.

**Comment by MikeBazMSFT** [comment]
Thanks for filing this!  I’m not sure how this wasn’t caught in the testing – it seems pretty directly broken – but I can’t be sure until someone on this end goes through and figures out how it was missed.  (I’d rather understand how we got here before just making the change.)  The “create the resource with a lowercase name” feels like the better fix here with a note added if they miss it about fixing /etc/hostname but we’ll take a closer look.

**Comment by darenm** [comment]
We are in the process of renaming all resources and will use lowercase naming conventions as recommended here: [Recommended naming and tagging conventions](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging#resource-naming)

**Comment by ChrisHowd** [comment]
vm names updated to lower case
