### ISSUE TITLE
C# code in lab2

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#31]
# Module: 1
### Ex: 1
Description of issue:
Was mentioned some C# code, but there is no C# code in this lab starter/setup folders.

Could you remove this snippet to avoid confusion.
![image](https://user-images.githubusercontent.com/578954/79833539-354fde00-83b4-11ea-835a-f44be1a57d92.png)

**Comment by MikeBazMSFT** [comment]
The instructions state that they are for the entire course:

> Throughout this course you will be creating resources

Therefore I don't believe removing those instructions would be appropriate.  There's not any `bash` scripts in this lab either.

I'm not closing yet to see if others have different thoughts.

**Comment by SychevIgor** [comment]
first lab where used C# - is lab 4. it's not just my opinion, it's a feedback that give me my group today.

**Comment by MikeBazMSFT** [comment]
Well as I said the same thing applies to `bash` - did they bring that same thing up?  I don't think it makes sense to remove `C#` from the starting overview not `bash` when they both have the same thing going on - so we remove both and move it (and duplicate it across labs and get complaints about that) or leave it here with the statement that is already there that it applies to the whole course.

**Comment by ChrisHowd** [comment]
the instructions will be updated to clearify that the naming conventions and unique ID information applies to labs 2-20. C# and Bash references will be kept in place.
