### ISSUE TITLE
using old AZ CLI extension

### ISSUE THREAD

**Issue by AndreaScarinci** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#34]
Using the old extension _azure-iot-cli-ext_ instead of the new recommended one _azure-iot_

source:
https://docs.microsoft.com/en-us/azure/iot-dps/how-to-manage-dps-with-cli

**Comment by ChrisHowd** [comment]
Thanks for pointing this out. It will be corrected in the next course update.
