### ISSUE TITLE
Lab 12: TLS authentication error

### ISSUE THREAD

**Issue by pietrobr** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#35]
I had to update to IoTEdge version 1.0.9  (from 1.0.8) to solve  TLS authentication error as reported [here](https://github.com/Azure/iotedge/issues/2910) 

ssh in the  IoTEdge Gateway VM before changing the config.yaml

```
curl -L https://github.com/Azure/azure-iotedge/releases/download/1.0.9/libiothsm-std_1.0.9-1_ubuntu16.04_amd64.deb -o libiothsm-std.deb && sudo dpkg -i ./libiothsm-std.deb
curl -L https://github.com/Azure/azure-iotedge/releases/download/1.0.9/iotedge_1.0.9-1_ubuntu16.04_amd64.deb -o iotedge.deb && sudo dpkg -i ./iotedge.deb
```
and then update your config.yaml and finally restart IoTEdge:

```
systemctl restart iotedge
```

**Comment by ChrisHowd** [comment]
thanks for identifying this issue and the fix.

**Comment by MikeBazMSFT** [comment]
Lab 12 has been updated to include instructions on updating to 1.0.9 so I'm closing this issue.  Thanks again @pietrobr for calling out the issue and the fix.
