### ISSUE TITLE
Install Azure CLI Extensions in Lab03 outdated

### ISSUE THREAD

**Issue by Maarten-Work** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#36]
# Module: 00
#### Step: 02

Description of issue:

In Lab 3, Task 2, Step 2 (Setup the Development Environment) it is suggested to install the Azure CLI Extension for IoT through: **az extension add --name azure-cli-iot-ext**. However, it looks like moving forward, this extension has been renamed to azure-iot (same functionality but higher version number of 0.9.1 today). Normally I would not have commented on version numbers, but with a change in name of the extension this is probably significant. So my suggestion in step 2 is to change the description into:

install the Azure CLI Extension for IoT through: **az extension add --name azure-iot**

and change the image in task 3, step 2 accordingly. I have marked the outdated versions in the attached images.

![Lab3-Exc2-Task2-Step2](https://user-images.githubusercontent.com/25533447/81914003-04d51b80-95d1-11ea-9e6b-74b16fa2b2de.jpg)

![Lab3-Exc2-Task3-Step2](https://user-images.githubusercontent.com/25533447/81914048-11f20a80-95d1-11ea-829f-99cd1ff70868.jpg)

Repro steps: N/A

**Comment by MikeBazMSFT** [comment]
Ah yeah this is a miss - the course materials have a note on this and have the right, newer, one mentioned, but the lab instructions didn't get caught.  Thanks for pointing it out.  Leaving this open until we sort it.

**Comment by MikeBazMSFT** [comment]
@darenm @ChrisHowd I believe this is a safe swap with no negative impact for the labs from this point forward, do you concur?

**Comment by ChrisHowd** [comment]
This has been updated, along with other non-breaking issues, in a GitHub branch that will be merged into Master next week. I addressed this in the student guide content (skillpipe) and the PowerPoint presentation a week or two ago, but held off on the labs because I grouped it with other updates.
