### ISSUE TITLE
 typo in routing query

### ISSUE THREAD

**Issue by chmagitt** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#38]
# Module: 04
#### Step: 03

Description of issue
 typo in routing query for the logging route in IoT hub

Repro steps:
this querry does not  work  sensorID = "VSLog"
this query works  sensorID = 'VSLog'

**Comment by ChrisHowd** [comment]
Thanks for the feedback. This will be reviewed/updated shortly.
