### ISSUE TITLE
Lab 17- Error System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0,

### ISSUE THREAD

**Issue by pietrobr** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#39]
If I try to restore .net project I get this error:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0,

I solved updating SimulatedDevice.csprj with the following

`
<ItemGroup>
    <PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.25.0" />
    <PackageReference Include="Microsoft.Azure.Devices.Provisioning.Transport.Mqtt" Version="1.2.2" />
    <PackageReference Include="Microsoft.Azure.Devices.Provisioning.Transport.Amqp" Version="1.2.2" />
    <PackageReference Include="Microsoft.Azure.Devices.Provisioning.Transport.Http" Version="1.2.2" />
 </ItemGroup>
`

**Comment by darenm** [comment]
Unable to reproduce the issue, however moved to star versioning in the project to ensure the latest 1.* packages are used.
