### ISSUE TITLE
Run dotnet restore prior to examining the program.cs source file

### ISSUE THREAD

**Issue by mstruys** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#4]
# Module: 00
#### Step: 04

Description of issue
Just opening program.cs in VS Code results in lots of errors (can't find classes etc.). Running **dotnet restore** solves this, so it makes sense to add this as an additional step after step 04.

**Comment by MikeBazMSFT** [comment]
Thanks for that idea.  It's probably a fair point across a lot of labs - so I'm going to leave this open for the moment as we go through them all.  `dotnet build` does this automatically, so it doesn't break the lab _per se_, but it is a source of confusion.

**Comment by darenm** [comment]
Added steps to restore packages.
