### ISSUE TITLE
Errors in lab 20 iot central

### ISSUE THREAD

**Issue by luiscantero** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#42]
# Module: 20
#### Step: 5-6

Steps 5 and 6 should be done the other way around. First enter the name and then create.

#### Step: 10

desiredProperties[setting]["value"] throws System.InvalidOperationException, "Cannot access child value on ...". Changing both occurrences to just "desiredProperties[setting]" fixes the problem.

![image](https://user-images.githubusercontent.com/1353540/87300562-57b64b00-c50e-11ea-83e3-84b5bec5f4d6.png)

**Comment by darenm** [comment]
Thanks for the report - I'll take a look.
