### ISSUE TITLE
A complete list of needed resource providers is not supplied.

### ISSUE THREAD

**Issue by MikeBazMSFT** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#45]
# Module: (all)
#### Step: n/a

Description of issue

We are seeing Microsoft Partners trying to use these labs for self-study outside of an ILT context, and hitting roadblocks around subscription lockdowns.  In a classroom environment, this isn't an issue, but in the "random subscription" context, this is problematic.  

I don't believe the fix is to document all the requirements in a subscription, because that can too easily get out of date as labs are modified, added, removed, etc.  Also, the labs were never intended to address that circumstance.

Instead, I propose a disclaimer in the Readme with a pointer to material designed directly for self-study.  Pull request #44 is an attempt to satisfy that goal.

**Comment by ChrisHowd** [comment]
Thanks Michael. I merged the pull request with your suggested wording. Hopefully this explanation and the link to Learning Paths will provide sufficient additional guidance. I suspect that a mapping of the MS Learn Modules to the ILT labs will be the next request. Oh well...
