### ISSUE TITLE
Content Directory: Lab Numbering issue

### ISSUE THREAD

**Issue by SteveSilver** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#49]
# Module: 00
#### Step: 00

Description of issue: There is no Lab numbered 19 listed in the content directory. However there is a lab 20. Perhaps the lab 20 should be changed to lab 19?

https://microsoftlearning.github.io/AZ-220-Microsoft-Azure-IoT-Developer/

Repro steps:

1.
1.
1.

**Comment by MikeBazMSFT** [comment]
Lab 19 is reserved as a placeholder.
