### ISSUE TITLE
Demo : Deploying an ARM Template appears to be a placeholder and not actual content.

### ISSUE THREAD

**Issue by SteveSilver** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#50]
# Module: 00
#### Step: 00

Description of issue It appears that Demo : Deploying an ARM Template that is listed at the bottom of the below page is a placeholder and not actual content. Perhaps it should be corrected or removed?

https://microsoftlearning.github.io/AZ-220-Microsoft-Azure-IoT-Developer/

Repro steps:

1.
1.
1.

**Comment by MikeBazMSFT** [comment]
The demos have not been created yet.
