### ISSUE TITLE
LAB_AK_05-individual-enrollment-of-device-in-dps Exercise 3

### ISSUE THREAD

**Issue by SteveSilver** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#51]
# Module: 02
#### Step: 02

Description of issue: There appears to be two Task 2 listed in Exercise 3. The first Task 2 is "Add the Provisioning Code" The Second Task 2 is "Integrate Device Properties" this appears from the lab that this should be Task 3.

Repro steps:

1.
1.
1.

**Comment by darenm** [comment]
Thanks for the report.
