### ISSUE TITLE
Lab-15 exercise 2 device not able to send telemetry

### ISSUE THREAD

**Issue by nikunj-phutela** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#52]
I have followed the steps mentioned at https://microsoftlearning.github.io/AZ-220-Microsoft-Azure-IoT-Developer/Instructions/Labs/LAB_AK_15-remotely-monitor-and-control-devices.html#simplified-lab-conditions but there is an issue whilst doing task 3 in exercise 2, where the device sends telemetry to the IOT Hub. The errors are as follows:
1. **warning MSB3101: Could not write state file "obj\Debug\netcoreapp3.1\cheesecavedevice.csprojAssemblyReference.cache". The file 'C:\Users\Asus\Downloads\AZ-220-Microsoft-Azure-IoT-Developer-master\AZ-220-Microsoft-Azure-IoT-Developer-master\Allfiles\Labs\15-Remotely monitor and control devices with Azure IoT Hub\Starter\cheesecavedevice\obj\Debug\netcoreapp3.1\cheesecavedevice.csprojAssemblyReference.cache' already exists.**
2. **Invalid runtimeconfig.json** [C:\Users\Asus\Downloads\AZ-220-Microsoft-Azure-IoT-Developer-master\AZ-220-Microsoft-Azure-IoT-Developer-master\Allfiles\Labs\15-Remotely monitor and control devices with Azure IoT Hub\Starter\cheesecavedevice\bin\Debug\netcoreapp3.1\cheesecavedevice.runtimeconfig.json] [C:\Users\Asus\Downloads\AZ-220-Microsoft-Azure-IoT-Developer-master\AZ-220-Microsoft-Azure-IoT-Developer-master\Allfiles\Labs\15-Remotely monitor and control devices with Azure IoT Hub\Starter\cheesecavedevice\bin\Debug\netcoreapp3.1\cheesecavedevice.runtimeconfig.dev.json]

Can somebody please help me with this?
![image](https://user-images.githubusercontent.com/41740876/89801911-5e0c0700-db4e-11ea-98f3-4d3974766830.png)

**Comment by darenm** [comment]
This looks like a transitory issue with Visual Studio Code. Try closing all instances of Visual Studio Code and delete the following folders:
* C:\Users\Asus\Downloads\AZ-220-Microsoft-Azure-IoT-Developer-master\AZ-220-Microsoft-Azure-IoT-Developer-master\Allfiles\Labs\15-Remotely monitor and control devices with Azure IoT Hub\Starter\cheesecavedevice\bin
* C:\Users\Asus\Downloads\AZ-220-Microsoft-Azure-IoT-Developer-master\AZ-220-Microsoft-Azure-IoT-Developer-master\Allfiles\Labs\15-Remotely monitor and control devices with Azure IoT Hub\Starter\cheesecavedevice\obj

Then rebuild your application with:

```powershell
dotnet build
```

**Comment by nikunj-phutela** [comment]
I tried removing the bin and the obj folder, but I could only cure the warning MSB3101 error,  but the other error, which is the first one, but I was not able to cure the invalid runtimeconfig.json error, would you be able to help with this too?

**Comment by darenm** [comment]
What version of .Net Core do you have installed? 
* Open a command prompt.
* Change directory to **C:\Users\Asus\Downloads\AZ-220-Microsoft-Azure-IoT-Developer-master\AZ-220-Microsoft-Azure-IoT-Developer-master\Allfiles\Labs\15-Remotely monitor and control devices with Azure IoT Hub\Starter\cheesecavedevice**
* Enter the following command:

```powershell
dotnet —-version
```

Also, please attach a copy of the invalid runtimeconfig.json.

**Comment by nikunj-phutela** [comment]
I have figured out my error, there was an issue with the length of the path, which led to the runtimeconfig.json file not being read, thank you so much for your help! @darenm

**Comment by darenm** [comment]
Great job figuring it out!
