### ISSUE TITLE
Exercise 5 step 9-10 unclear as to steps

### ISSUE THREAD

**Issue by SteveSilver** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#53]
# Module: 03
#### Step: 09-10

Description of issue: There is no direction to  where to enter "image URI" per the steps. Please clarify

Repro steps:

1.
1.
1.

.
9. On the Add IoT Edge Module pane, under IOT Edge Module Name, enter tempsensor
We will be naming our custom module “tempsensor”
10. Under Image URI, enter asaedgedockerhubtest/asa-edge-test-module:simulated-temperature-sensor

**Comment by darenm** [comment]
When the field is visible on the screen, we typically don't provide additional information to locate it, so I wonder if you have perhaps opened a different UI? This is the view I see with the field highlighted:
![image](https://user-images.githubusercontent.com/1674843/89941539-66108900-dbd8-11ea-9d90-9bb4d96c22ea.png)
