### ISSUE TITLE
Lab 12 update breaks authentication with CA certificate and affects associated module on MSLearn Platform

### ISSUE THREAD

**Issue by toolboc** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#56]
# Module: [Set up an IoT Edge Gateway](https://docs.microsoft.com/en-us/learn/modules/set-up-iot-edge-gateway/)
#### Step: 04

Commit ca2cfbe89669f8440100657eb65dcfe6f9a87193  renames `Downstreamdevice.csproj` to `CaveDevice.csproj` and includes a removal of the following in the .proj file:

`
<ItemGroup>	
    <None Update="azure-iot-test-only.root.ca.cert.pem" CopyToOutputDirectory="PreserveNewest" />	
  </ItemGroup>
`

The removal of the `<ItemGroup/>` entry breaks the ability to authenticate the IoT Device using a CA certificate (which is a key requirement for Lab 12.  In addition, this change has broken the associated module on MS Learn @ https://docs.microsoft.com/en-us/learn/modules/set-up-iot-edge-gateway/8-connect-downstream-device-iot-edge-gateway

Suggestions:

1. Revert commit ca2cfbe89669f8440100657eb65dcfe6f9a87193 to fix the affected Lab content and associated Learn Module (This suggestion assumes that it is far easier to fix the issue here than submit a re-review to the Learn team)
2. Create a new folder for CaveDevice.proj if it is needed

**Comment by darenm** [comment]
@toolboc 

Thanks for raising the issue - we will certainly address the missing `<ItemGroup>` element. In terms of the MS Learn dependency on this content, Worldwide Learning will work with the MS Learn team to determine the best way forward.
