### ISSUE TITLE
Lab 10 - Run Simulated devices failing

### ISSUE THREAD

**Issue by SurbhiAgarwal12** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#57]
# Module: 00
#### Step: 00

Description of issue
In Visual Studio Code, I have edited the right Connection Strings and when I ran the program "dotnet run" it failed with the error -"Invalid runtimeconfig.json [C:\AZ-220-Microsoft-Azure-IoT-Developer-master\AZ-220-Microsoft-Azure-IoT-Developer-master\Allfiles\Labs\10-Explore and analyze time stamped data with Time Series Insights\Starter\ContainerSimulation\bin\Debug\netcoreapp3.1\ContainerSimulation.runtimeconfig.json] [C:\AZ-220-Microsoft-Azure-IoT-Developer-master\AZ-220-Microsoft-Azure-IoT-Developer-master\Allfiles\Labs\10-Explore and analyze time stamped data with Time Series Insights\Starter\ContainerSimulation\bin\Debug\netcoreapp3.1\ContainerSimulation.runtimeconfig.dev.json]"

Can you guide how to resolve this issue?
Repro steps:

1.
1.
1.

**Comment by MikeBazMSFT** [comment]
Is this the same issue that was in #52 (found with a search), where the path is too long?  It looks long.

**Comment by darenm** [comment]
@SurbhiAgarwal12  @MikeBazMSFT Yes - it is too long: 262 characters vs. the max of 256. I'll add a note to Lab 3, Exercise 3, Task 1 noting the restriction and advising renaming the root folders of the extracted zip.

**Comment by SurbhiAgarwal12** [comment]
Thank you so much, after renaming the path it worked.
