### ISSUE TITLE
Exercise 3 Step 24 in Lab 17 in correctly named.

### ISSUE THREAD

**Issue by SteveSilver** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#59]
# Module: 00
#### Step: 24

Description of issue "Reads Under Short name, enter AZ220EmailAG. There is no "short name" there is however "Display Name.

Repro steps:

1.Under Display Name, enter AZ220EmailAG
1.
1.

**Comment by darenm** [comment]
Thanks for the report. These changes happen as the Azure UI is continually refined.
