### ISSUE TITLE
lab-setup.azcli missing in lab07

### ISSUE THREAD

**Issue by mstruys** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#6]
# Module: 00
#### Step: 00

Description of issue

lab-setup.azcli seems to be missing in lab 07.

**Comment by MikeBazMSFT** [comment]
Thanks, this is a known issue in this lab and I think at least one other - there's multiple issues around the lab setup scripts right now (including that we don't tell you clearly where to get them).  I'm leaving this open until get it sorted.

**Comment by darenm** [comment]
**lab-07-setup.azcli** has been added and the lab content has be updated to specify the location.
