### ISSUE TITLE
Lab 17 How to Manage your Iot Hub Task 3 Step 27 incorrect making lab not viable

### ISSUE THREAD

**Issue by SteveSilver** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#60]
# Module: 09
#### Step: 27, 28, 29

Description of issue: Step 29 in the Action Type dropdown, click Email/SMS/Push/Voice this apparently has been moved to "Notifications" blade and is no longer listed under Actions but under Notifications. 

Under the current lab instructions the lab is not viable. Action blade no instructions what to do under current version.

Repro steps:

1.
1.
1.

**Comment by darenm** [comment]
Thanks for this issue. It appears the team decided to break out notifications from the integration actions and have refactored the UI.
