### ISSUE TITLE
Lab 8 misslabeling of file

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#61]
# Module: 05
#### Step: 04

Description of issue
It reads "Click VibrationSensor, and then click Select Folder." However there is only a folder named "VibrationDevice" and the project is also called "VibrationDevice" instead of sensor. In task 8 "VibrationDevice" is used so probably the right value.

Repro steps:
Rename "VibrationSensor" to "VibrationDevice" on Task 4 (bold) and also in the line below rename "VibrationSensor.csproj" to "VibrationDevice.csproj".

**Comment by darenm** [comment]
Thanks for the report.
