### ISSUE TITLE
Lab 8 broken link to console output

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#62]
# Module: 05
#### Step: 10

Description of issue
The link to the "Console Output" image (png) is not working.

Repro steps:
Upload the Console Output image (LAB_AK_08-vibration-telemetry.png) to the right folder

**Comment by darenm** [comment]
Thanks for the report. It transpires that the image links are case sensitive when published via GitHub IO.
