### ISSUE TITLE
Lab 8 - resources were already created by script

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#63]
# Module: 05
#### Step: all

Description of issue
Resources in Task 01 and 02 were already created by the script we ran at the beginning of the lab. 
However Task 2 has different values (Partition count set to 4 instead of 1 and Message Retention set to 7 instead of 1)

Repro steps:
1. Make a note in Task 1 and 2 that this resource was created and that the student should explore the information/screens.
2. Adjust the ARM template from the beginning of the lab to set partition count and message retention to the listed values.

**Comment by darenm** [comment]
Thanks for the report. As we would prefer the user create the resources, the setup script will be modified.
