### ISSUE TITLE
Missing command-piece

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#65]
# Module: 03
#### Step: 07

Description of issue
The command reads
download ~/certificates/certs/azure-iot-test-only.root.ca.cert.pem

We loaded the files though into a folder "lab6" so the command should read

Repro steps:
download ~/lab6/certificates/certs/azure-iot-test-only.root.ca.cert.pem

**Comment by darenm** [comment]
Thanks for the report - I can see how this The actual intent of **Lab 6 / Exercise 2 / Task 1 : Generate the certificates** is that the user is located in their home directory when they create the **certificates** directory - the lab6 directory is just used for the setup files. I will clarify this in the steps.
