### ISSUE TITLE
Lab15 - update to setup script 

### ISSUE THREAD

**Issue by Raregine** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#66]
# Module: 00
#### Step: 00

Description of issue:
Slight update required to CLI command at end of setup script to display device connection string. Change from:

echo "$DeviceID device connection string:"
az iot hub device-identity connection-string **show** --hub-name $IoTHubName --device-id $DeviceID -o tsv
echo ""

to: 

echo "$DeviceID device connection string:"
az iot hub device-identity **show-connection-string** --hub-name $IoTHubName --device-id $DeviceID -o tsv
echo ""

Getting the following error at the moment 

_sensor-th-0055 device connection string:
az iot hub device-identity: 'connection-string' is not in the 'az iot hub device-identity' command group. See 'az iot hub device-identity --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview

The most similar choice to 'connection-string' is:
        show-connection-string_

**Comment by darenm** [comment]
You are using a deprecated version of the azure iot cli extension - please update to the latest version. 

The legacy IoT extension Id **azure-cli-iot-ext** is deprecated in favor of the new modern Id **azure-iot**. **azure-iot** is a superset of **azure-cli-iot-ext** and any new features or fixes will apply to **azure-iot** only. Also the legacy and modern IoT extension should never co-exist in the same CLI environment.

### Docs
Deprecated version - [overview docs](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/?view=azure-cli-latest)
New version - [overview docs](https://docs.microsoft.com/en-us/cli/azure/ext/azure-iot/?view=azure-cli-latest)

Documentation for the new connection string format: [az iot hub device-identity connection-string show](https://docs.microsoft.com/en-us/cli/azure/ext/azure-iot/iot/hub/device-identity/connection-string?view=azure-cli-latest)

### Update
Steps to remove the old version and install the new version:
```bash
az extension remove --name azure-cli-iot-ext
az extension add --name --name azure-iot
```
