### ISSUE TITLE
Lab10 Exercise 4  -incorrect - please fix

### ISSUE THREAD

**Issue by SteveSilver** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#67]
# Module: 00
#### Step: 00

Exercise 4

Repro steps:

1.Exercise 4 is of lab 10 is not doable using the directions here. Perhaps TSI was updated but the instructions here are incorrect
1.
1.

**Comment by darenm** [comment]
Azure TSI Gen2 has recently shipped resulting in minor UI changes. The lab has been updated to ensure that the **Gen1 (S1)** tier is selected and to note that **Go to Environment** has been renamed to **Go to TSI Explorer**.
