### ISSUE TITLE
Lab 19  / Exercise 6 / Task 1 : There seems to be no Resources  under Security in IoT Hub.

### ISSUE THREAD

**Issue by veryblue1118** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#69]
# Module: 00
#### Step: 2

Description of issue

The step is saying "On the left-side menu, under Security, click Resources." like the below
```
2. On the left-side menu, under Security, click Resources.

Note that the list of resources already includes your IoT Hub, the workspace that was created when Azure Security Center for IoT was activated earlier as well as the current subscription.
```

But there seems to be no "Resources" under the Security of IoT Hub.

![image](https://user-images.githubusercontent.com/72372443/95496445-d28ee500-09db-11eb-8e2d-e2e7bd81e2c8.png)

Repro steps:
Instead of the step, I could find "Resources" from  "Settings" 

1.  On the left-side menu, under Security, click Settings.
![image](https://user-images.githubusercontent.com/72372443/95496634-108c0900-09dc-11eb-88eb-adf73f8ddde4.png)

2. Click "Monitored Resources" Under Name in Setting Page
![image](https://user-images.githubusercontent.com/72372443/95496774-46c98880-09dc-11eb-8829-b4aced3d9ebf.png)

3, You can see "Resources"

![image](https://user-images.githubusercontent.com/72372443/95496920-7c6e7180-09dc-11eb-97f3-53a159be4a3b.png)

4. After that, I could follow the next step.
```
3. At the top of the pane, click Edit.

The Solution Management pane opens, where you can connect additional Azure resources to your security solution by selecting their owning resource groups.
```
![image](https://user-images.githubusercontent.com/72372443/95497101-c7888480-09dc-11eb-89a1-fc8e12b4b1d4.png)

**Comment by darenm** [comment]
Thanks for the report. It appears the Azure UI has been refined to consolidate items within the **Settings** pane. We will update the content to reflect the change.
