### ISSUE TITLE
Use of both routing direct to blob and stream analytics job is confusing

### ISSUE THREAD

**Issue by creationsoft** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#7]
# Module: 00
#### Step: 00

Description of issue
IMHO the lab is confusing as it uses two different methods to achieve essentially the same thing in parallel (unless I've missed something).
Perhaps we should specify that the user picks 'JSON' as the output format for the blob message route so the user can easily inspect the information using notepad.
Also I believe the statement 'To verify that the logging route is working as expected, we will create a Stream Analytics job that routes logging messages to Blob storage.' to be misleading. Verifying that the logging route is working would be a matter of using storage explorer (which is used later on)

Repro steps:

1.
1.
1.

**Comment by MikeBazMSFT** [comment]
Thank you for your feedback here.  It's fair that the explanation of the dual paths to storage is lacking; I've added some text in to Lab 7 Exercise 4's introduction to hopefully address what you're saying here.  I'm leaving this open for now until hearing back.

**Comment by darenm** [comment]
The additional notes in the content explain why the dual paths are added:

> **Note**: It may seem odd that in this lab we are routing data to storage, and then also sending our data to storage through Azure Stream Analytics. In a production scenario, you wouldn't have both paths long-term. Instead, it is likely that the second path that we're creating here would not exist. We're using it here, in a lab environment, as a way to validate that our routing is working as expected and to show a simple implementation of Azure Stream Analytics.

The lab will remain as-is for the initial version - however we will watch for additional feedback.
