### ISSUE TITLE
Code Change

### ISSUE THREAD

**Issue by ClarkDRC** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#71]
# Module: 00
#### Step: 02

Description of issue:
Change code to change &lt; to < and &gt; to >

Repro steps:

**Comment by ChrisHowd** [comment]
It is unclear what issue you are hoping we can address.

Your description of issue "Change code to change < to < and > to >" does not describe an issue and does not result in any change.

**Comment by ClarkDRC** [comment]
True Type is typing & g t ; and & l t ; with out the spaces instead of > and <

**Comment by ChrisHowd** [comment]
As you may expect, rendering of the markdown instructions is done in the UI. Are you seeing this issue in the LODS environment? If not, what environment are you using to view the lab instructions?

**Comment by ClarkDRC** [comment]
Yes this is in the LODs environment.

**Comment by ChrisHowd** [comment]
I will notify a point of contact with LODS that they have a rendering issue with their UI. I believe that there is a way for you to notify LODS directly through their UI and I suggest that you do so for any issue that you believe could be related to their environment. When I raise issues to them I consistently hear that they have not received any escalations related to this course.
