### ISSUE TITLE
Code Change

### ISSUE THREAD

**Issue by ClarkDRC** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#72]
# Module: 00
#### Step: 14

Description of issue
Change code to change &gt; to >

Repro steps:

1.
1.
1.

**Comment by ChrisHowd** [comment]
Please provide a more actionable description of the issue that you are reporting. The description above "Change code to change > to >" does not describe the issue and does not result in a change.

**Comment by ClarkDRC** [comment]
True Type creates '&gt;' in the code instead of >

**Comment by ClarkDRC** [comment]
I'm truing to say & g t ; with out the spaces :-)

**Comment by ChrisHowd** [comment]
Thanks for identifying this issue. Since this is an LODS issue rather than a lab instructions/content issue, it will be closed here and will be raised to LODS.
