### ISSUE TITLE
Lab 7, Exercise 4, Step 9 & 10 - ASA Stores the blobs directly in the container.

### ISSUE THREAD

**Issue by tinodo** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#78]
# Module: 04
#### Step: 09

The manual indicates that ASA stores the blob in a 'folder hierarchy'. That is what IoT Hub uses when you use a storage endpoint, but ASA stores the blobs directly in the 'root' of the container. Hence, there is no 'navigating to it'.

Repro steps:

1.Run the lab and look at the container in the storage account; there is no folder hierarchy.

**Comment by darenm** [comment]
We shall update the content as appropriate.
