### ISSUE TITLE
The Filters tab of your event subscription should now look similar to this image:

### ISSUE THREAD

**Issue by gerhard67** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#8]
# Module: 05
#### Step: 6

Description of issue
you write "The Filters tab of your event subscription should now look similar to this image:"
But there is no image. On top, all other images missing and you got 404 if you click on it.

**Comment by AltaOhms** [comment]
Thanks Gerhard! The instruction labs are strip down versions without images, so thanks for catching this. The labs under MSLearn folder has the photos. I will update the language in the strip down versions. In short, the classroom VM doesn't allow images and why we had to split the labs. :)

**Comment by darenm** [comment]
The images have been restored to LAB_AK_09-iot-hub-integration-with-azure-event-grid.
