### ISSUE TITLE
System Topic Name Required Field

### ISSUE THREAD

**Issue by rlthompson904** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#81]
# Module: 09
#### Step: 07

Description of issue: Currently states 

Leave the TOPIC DETAILS section unchanged.

This section is informational and read-only

System Topic Name is a Required field

Repro steps:

1.
1.
1.

**Comment by rlthompson904** [comment]
Is this issue being addressed?

**Comment by darenm** [comment]
The content in the TOPIC DETAILS section should be auto-populated during the creation. Are you seeing this issue in the context of delivering the course to a number of students. Are all students seeing the issue?

**Comment by rlthompson904** [comment]
We recently discovered this seems to be a bug when using legacy edge in Azure, the content is working as it should just need to update our images. Thank you for your reply.
