### ISSUE TITLE
macOS - System.Security.Cryptography.CryptographicException: Access is denied.

### ISSUE THREAD

**Issue by jiaher** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#82]
# Module: 06
#### Step: 16

Description of issue

I'm going through the exercise on my Mac (Catalina 10.15.7) .At step 16 of exercise 9, when I run `dotnet run` as per instruction, I obtained the following:

![image](https://user-images.githubusercontent.com/691698/105825521-a6cf5380-5ffa-11eb-9c35-595af7bdc352.png)

I did not change any of the source code in _Program.cs_ except to update the connectionString variable.
Not sure what else I can do.

**Comment by darenm** [comment]
These labs are designed to be run in a learning-on demand virtual environment (that uses Windows 10) as part of an MCT (Microsoft Certified Trainer) training course. This site provides support for the MCTs and that environment,so I am going to close this issue. If you are an MCT and encounter the issue in the target environment, please create a new issue.
