### ISSUE TITLE
Update terminology Lab 02, Module 01, Exercise 2, Task 2, Step 9

### ISSUE THREAD

**Issue by LodsCory** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#83]
# Module: 01
#### Step: 09

Description of issue
Step says "To the right of **Azure Security Center**, ensure that **Off** is selected." Azure Security Center is now Defender for IoT. This seems to be tripping some people up.

Repro steps:

1. Go to the management tab when creating an IoT hub.
1.
1.

**Comment by darenm** [comment]
Last time we reviewed the content, we found that product is named **Defender for IoT** in some places, and still named **Azure Security Center** elsewhere. We shall take a look to see if the rollout has now completed and we can update globally. If not, we shall try to note the inconsistencies.

**Comment by LodsCory** [comment]
Thank you for the prompt response.

**Comment by darenm** [comment]
@LodsCory Thank you for the issue - the documentation and UI is more consistent now than the last time it was reviewed and the content has been updated to reflect that.
