### ISSUE TITLE
Typo in Lab 2

### ISSUE THREAD

**Issue by sthoward0914** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#84]
# Module: 02
#### Step: 09 (Tip)

Description of issue
Currently, the tip reads

TIP: Azure Defender for IoT was formally known as Azure Security Center and you may still see places in Azure, and in this content, where the name has not yet been updated.

"Formally" is incorrect in this sentence. You mean to say that it was "formerly known" or "previously known" as Azure Security center.

**Comment by darenm** [comment]
Thanks for this issue.
