### ISSUE TITLE
Lab 15 Console Outputs are missing

### ISSUE THREAD

**Issue by deomaximo** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#85]
# Module: 08
#### Step: 02

Description of issue

Console Outputs are missing. Error 404

Repro steps:

Clicked out Console Output hyperlink got 404
--------------------------------------------------
Same for 
# Module: 08
#### Step: 04, 05

Description of issue

Console Outputs are missing. Error 404

Repro steps:

Clicked out Console Output hyperlink got 404

**Comment by darenm** [comment]
Thanks for the issue.
