### ISSUE TITLE
can't select active subscription 

### ISSUE THREAD

**Issue by mhykgyver** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#86]
# Module: 07
#### Step: 08

Description of issue: Upon adding a module, student can't select active subscription, it took him  a lot of tries and eventually the active subscription was available for selection. 

Repro steps: (as per lab steps for Lab 11, Exercise 5)

1. On your Resource group tile, to open your IoT Hub, click iot-az220-training-{your-id}.
2. At the left of the IoT Hub blade, under Automatic Device Management, click IoT Edge.
3. On the list of IoT Edge Devices, click sensor-th-0067.
4. On the sensor-th-0067 blade, notice that the Modules tab displays a list of the modules currently configured for the device.
Currently, the IoT Edge device is configured with only the Edge Agent ($edgeAgent) and Edge Hub ($edgeHub) modules that are part of the IoT Edge Runtime.
6. At the top of the sensor-th-0067 blade, click Set Modules.
7. On the Set modules on device: sensor-th-0067 blade, locate the IoT Edge Modules section.
8. Under IoT Edge Modules, click Add, and then click IoT Edge Module.

![2021-02-10_02-53](https://user-images.githubusercontent.com/12806459/107458070-4dd0f500-6b8e-11eb-9799-c2a326756bc6.png)

**Comment by darenm** [comment]
What browser is the student using? Legacy Edge has some problems with Azure and often doesn't set the appropriate default values, so try the latest Edge browser. Other than that, this appears to be an issue with Azure itself, rather than the course steps.
