### ISSUE TITLE
microsoft.insights not registered

### ISSUE THREAD

**Issue by mhykgyver** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#87]
# Module: 09
#### Step: 43

Description of issue: error showing microsoft.insight is not registered

Repro steps:
perform the lab steps for Alerts

Solution: run az provider register --namespace 'Microsoft.Insights' before doing the labs as per reference to AZ-303 lab 5 module ( https://github.com/MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies/blob/master/Instructions/Labs/Module_05_Lab.md)

**Comment by darenm** [comment]
Registering the resource via the CLI should not be required when provisioning via the Azure Portal UI - the UI should enable the resource as part of the provisioning process. Did this issue occur with just one student or many?

**Comment by darenm** [comment]
Added registration of resource providers to Lab 3 and to the setup script for lab 17
