### ISSUE TITLE
missing packages for device simulator app

### ISSUE THREAD

**Issue by mhykgyver** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#88]
# Module: 08
#### Step: 03

Description of issue: build error for device simulator app

Repro steps:
1. Follow the lab steps 

Solution: as per student's remediation:
  - add packages to the project. (Ref https://docs.microsoft.com/en-us/dotnet/api/overview/azure/iot)

dotnet add package Microsoft.Azure.Device
dotnet add package Microsoft.Azure.Devices.Client

**Comment by darenm** [comment]
The **VibrationDevice.csproj** file already includes the required package - the student may have assumed that red-underlines displayed in the editor indicated that package references were missing, whereas they actually meant that the packages had not yet been restored. In terms of the lab instructions, the student is just asked to update the connection string and then execute the code via the `dotnet run` command. This will restore packages, build and the run the app.
