### ISSUE TITLE
Creating custom alerts don't work

### ISSUE THREAD

**Issue by Distinctlyminty** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#89]
# Module: 10
#### Step: 00

Following the steps for exercise 7 - Introducing custom alerts.  Having created a new custom alert and adding the security group tag to the device twin, the custom alert never fires.

I use the simulator code to flood the device with messages but no alert is ever raised in the threat dashboard.
I have tried with different hubs on different subscriptions and even tried different custom alert rules.  Including IP address not allowed.  No matter what I do I can't get a custom alert to trigger.

**Comment by darenm** [comment]
It does take quite some time for the alerts to surface up. I completed the lab today and didn't see the first alert until at least 30 minutes after running the simulator, and then the alerts appeared periodically:

![image](https://user-images.githubusercontent.com/1674843/114108387-3a8d8d80-9890-11eb-81cd-444729145eca.png)

**Comment by darenm** [comment]
Yes - definitely patience is key:
![image](https://user-images.githubusercontent.com/1674843/114111403-2f8a2b80-9897-11eb-929b-dba9f6062a1a.png)

![image](https://user-images.githubusercontent.com/1674843/114111356-184b3e00-9897-11eb-9e12-3e4c5d6a8bb6.png)

I will update the content with a note.

**Comment by Distinctlyminty** [comment]
Actually this was an issue with the back end in azure. Confirmed with a support ticket

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
