### ISSUE TITLE
"Azure IoT Edge on Ubuntu" doesn't exist in the Marketplace

### ISSUE THREAD

**Issue by AndyPT** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#90]
# Module: 06
#### Step: 03

Description of issue
"Azure IoT Edge on Ubuntu" doesn't exist in the Marketplace

Repro steps:

1. Clicking on "+ Create a resource" and searching for "Azure IoT Edge on Ubuntu" doesn't return a valid resource.

Recommended alternative is to create a generic Ubuntu VM, and then add the relevant steps in https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2018-06

**Comment by darenm** [comment]
Updated 11, 12 and 14.
