### ISSUE TITLE
No download confirmation

### ISSUE THREAD

**Issue by ClarkDRC** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#91]
# Module: 00
#### Step: 00

Description of issue
After clicking the download lab files link in the before you start section, no indication is given of progress and completion. 
Repro steps:
see diagram
![Capture1](https://user-images.githubusercontent.com/49040027/113882805-9d493100-978b-11eb-886c-7429851d29b5.PNG)

**Comment by darenm** [comment]
@ClarkDRC It appears that the LODS environment instructions included in the screen shot explicitly state:
> You will not see any output on screen.
Therefore, it appears the environment is working as expected. 
As this is not an issue with the course content, but rather how the LODS environment functions, I am closing this.

**Comment by LodsCory** [comment]
The lab files download in the Learn on Demand Systems environment will now have a button and will give a success status when complete.
