### ISSUE TITLE
AZ220 - Lab11 - Introduction to Azure IoT Edge - Issue on update (with solution)

### ISSUE THREAD

**Issue by JuanQuijano** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#94]
# Module: AZ-220-Microsoft-Azure-IoT-Developer
#### Step: 01.

Description of issue
sudo apt-get update

Repro steps:

1.Run in Cloud Shell this command
2. The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
3. The Moby installation fail.

Solution
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB3E94ADBE1229CF
Continue with the installation.

**Comment by darenm** [comment]
I am unclear where you are attempting to execute this command - this should be run while logged into the the VM, not just within the cloud shell. Can you confirm the issue occurs when you are logged into the VM?

**Comment by JuanQuijano** [comment]
Yes. Into VM. Some trouble with the public key.

Another problem is that the storage account cannot be configured in Stream Analytics and the lab cannot be continued. Always fail.
But I will write that in another issue, because it is an Azure problem, not the laboratory.

**Comment by darenm** [comment]
I have been unable to replicate this issue despite multiple attempts. I suspect there was a transient failure during **Task 2: Add the Microsoft installation packages to the package manager** that resulted in a problem. I shall close this - do  report if you encounter the problem again.
