### ISSUE TITLE
Lab 19: Download ZIP button for ADT Explorer not available at link

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#97]
# Module: 11
#### Step: 03

Description of issue
The instructions state to "click Download ZIP" but there's no such button. When navigating further to the GitHub repo the ZIP archive has a different name. Clarify how and where to download the archive.

Repro steps:

1. Open a browser and navigate to Azure Digital Twins (ADT) explorer.
1. To download the application, click Download ZIP.
1. The browser will download the Azure_Digital_Twins__ADT__explorer.zip file.

**Comment by darenm** [comment]
Looks like the ADT Explorer team updated that article last Friday and have changed how to install ADT Explorer. Follow the instructions here for now:

https://docs.microsoft.com/en-us/samples/azure-samples/digital-twins-explorer/digital-twins-explorer/

**Comment by darenm** [comment]
Updated the lab instructions with a link direct to the release ZIP.
