### ISSUE TITLE
Lab 19: Replace instructions need update

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#98]
# Module: 11
#### Step: 01

The instructions after the command line to copy state to replace {file-root} which is not part of the used command line.

"Ensure you replace the {file-root} with the folder the companion files for this lab are located, and replace {your-id} with your unique identifier."

All that needs to be replaced is {your-id}.

**Comment by darenm** [comment]
Fixed.
